name: YAML Check

on:
  push:
    branches:
      - main
    paths:
      - 'lake/**'

jobs:
  check_and_update:
    runs-on: alpine:latest
    steps:
    - uses: actions/checkout@v3

    - name: Cache lake directory
      uses: actions/cache@v2
      with:
        path: lake
        key: ${{ runner.os }}-lake-${{ hashFiles('lake/**/*.yaml') }}
        restore-keys: |
          ${{ runner.os }}-lake-

    - name: Install dependencies
      run: |
        apk add --no-cache git yamllint

    - name: YAML Lint
      run: yamllint -s -c .yamllint lake/*.yaml

    - name: Check and update YAML files
      run: |
        for file in ${{ github.workspace }}/lake/*.yaml; do
          filename=$(basename "$file" .yaml)
          
          # Check and add missing fields
          for field in id title tags description references why_not; do
            if ! grep -q "^$field:" "$file"; then
              echo "$filename: $field missing"
              echo "" >> "$file"
              case $field in
                id|title) echo "$field: $filename" >> "$file" ;;
                tags|references|why_not) echo -e "$field:\n  -" >> "$file" ;;
                description) echo "description:" >> "$file" ;;
              esac
            fi
          done
        done

    - name: Commit and push changes
      run: |
        git config --global user.email "tb@evait.de"
        git config --global user.name "NxtTAB"
        git add lake/*.yaml
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Worker check yaml"
          git push
        fi
      env: 
        ACCESS_TOKEN: ${{ secrets.Wami_Lake_yaml_check }}
