name: Generate Lake Hash Key

on:
  workflow_run:
    workflows: ["Yaml Check"]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  check_run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y coreutils
    
    - name: Calculate and store hash
      run: |
        find lake/* -name "*.yaml" -exec sha256sum {} + > /tmp/temp_hashes.txt
        cut -d ' ' -f 1 /tmp/temp_hashes.txt > /tmp/temp_hashes_only.txt
        cat /tmp/temp_hashes_only.txt | shs256sum | cut -d ' ' -f 1 > lake_hash.txt

    - name: Clean up
      run: |
        rm /tmp/temp_hashes.txt
        rm /tmp/temp_hashes_only.txt

    - name: Status
      run: |
        echo "SHA-256_hashvalue is" $(cat lake_hash.txt)
      env:
        ACCESS_TOKEN: ${{ secrets.Wami_Lake_yaml_check }}
    
    - name: Commit and push changes
      run: |
        git config --global user.email "tb@evait.de"
        git config --global user.name "NxtTAB"
        status=$(git status --procelain)
        if [ -n "$status" ];
          then
            git add lake_hash.txt
            git commit -m "Worker check yaml"
            git push
          else
            echo "Nothing to commit and push"
        fi